### ISSUE TITLE
Guake 3.2.2 does not have transparency

### ISSUE THREAD

**Issue by Moulick** [Guake/guake#1333]
I just updated from guake 0.8.8 in the ubuntu archives to 3.2.2 HEAD compiled from source. The 0.8.8 version had transparency but 3.2.2 does not. Is this a bug or a problem in my settings?

Gif attached.

![No transparency](https://user-images.githubusercontent.com/15780903/40335223-383251d6-5d80-11e8-9d43-75ae78d59f53.gif)

➜ guake --version
Guake Terminal: 3.2.2
VTE: 0.48.4
VTE runtime: 0.48.4
Gtk: 3.22.25

**Comment by gsemet** [comment]
which distribution are you using?

**Comment by Moulick** [comment]
Its Ubuntu 17.10

**Comment by Alsturm** [comment]
Same problem on Ubuntu 18.04

**Comment by fprawits** [comment]
I tried Guake3 for the first time (been a long-time 0.8 user) today and ran into the following two issues:

1) Transparency doesn't work with latest commit (3.2.1 in my case, I don't know where other people got the 3.2.2 release from)
=> this is fixed by git checkout to the 3.2.0 tag and compiling from there, so maybe there is a regression of some sort?

2) tray indicator is missing (both in 3.2.1 and 3.2.0, was working back in 0.8). since this isn't related to the issue here, I can start a separate 'issue' for this, but maybe this is already well known and someone can point me to the right place.

I am using ubuntu 16.04 (with x11, no wayland)

**Comment by Moulick** [comment]
@fprawits So just to clarify, the transparency issue is not there in ver 3.2.0?

**Comment by fprawits** [comment]
@Moulick Yes, after my initial fetch today (version 3.2.1) I was annoyed by the missing transparency and started trying out older versions. So when I built from 3.2.0 transparency worked as expected. The only thing I am currently missing is the mentioned indicator applet.

**Comment by Moulick** [comment]
Something weird just happened. As you did, I just tried out `git checkout tags/3.2.0`, compiled it, installed it. Now the transparency is back but `guake --version` still shows 3.2.2. How it that possible ???

![screenshot from 2018-05-29 02-31-27](https://user-images.githubusercontent.com/15780903/40629389-769d444a-62e8-11e8-9a51-88ba7d8ba89b.png)

**Comment by gsemet** [comment]
Do you have something in the log related to this transparency issue ?

**Comment by gsemet** [comment]
make reinstall

**Comment by fprawits** [comment]
quick follow-up: I just reattached my HEAD to the tip of the history (sitting at the top of the current commit `2908357bf851063dbac7e813dfa746a06e0ba469`), recompiled and the transparency issue is gone now as well! 

I noticed `guake/data`  showing up under untracked files when performing `git status`, is it possible that we imported something into our working directory when compiling from the 3.2.0 tag, that now makes the transparency work at the tip of master again?

**Comment by fprawits** [comment]
So the strange thing is, that I now cannot even recreate the initial bug. If I sudo make uninstall my current guake, clone the repo from GItHub into a new directory and compile from there everything (except for the indicator) works as expected.

**Comment by Moulick** [comment]
@fprawits Yeah, I have the tray indicator turned off as I didn't need it. 

Sometimes though my whole tray goes missing, but that's a bug in my setup, not guake.

I still don't get transparency when I compile HEAD but I have transparency for both tags/3.2.1 and tags/3.2.0.

@gsemet where can I get the logs?

**Comment by gsemet** [comment]
guake —debug

**Comment by TimKarsten** [comment]
RHEL 7.5,EPEL 7 guake package 

I'm missing working transparency as well.

`Name        : guake
Arch        : noarch
Version     : 0.8.7
Release     : 1.el7
Size        : 1.3 M
Repo        : installed
From repo   : epel
Summary     : Drop-down terminal for GNOME
URL         : http://guake-project.org/
License     : GPLv2+
Description : Guake is a drop-down terminal for Gnome Desktop Environment,
            : so you just need to press a key to invoke him,
            : and press again to hide.
`

**Comment by fprawits** [comment]
@Moulick: unfortunately my report of an issue-free tip was pre-mature. It seems like I still had the old (tag 3.2.0) guake running while compiling from the current source. After a reboot transparency is gone again, so I will probably switch to one of the older tags for now until this gets sorted out. Sorry for the confusion I might have caused.

**Comment by gsemet** [comment]
CAN one that have this issue bisect to get the commit that introduced the regression in the recent changes ? Under Ubuntu 16.04 i don’t have any issue with transparency on the latest version

**Comment by TimKarsten** [comment]
I have installed it as a package and this would be my first attempt to bisect an application, let alone compiling it on RHEL.

**Comment by Moulick** [comment]
@gsemet I am willing to do it. But can you please outline the steps to bisect the commits? Just to be sure that I don't make any missteps that might lead to the wrong conclusion...

**Comment by gsemet** [comment]
either your use [git bissect](https://git-scm.com/book/en/v2/Git-Tools-Debugging-with-Git), doing a `make reinstall` between each step. It is pretty fun to play with :)

Or you manually checkout each commit, make reinstall, start guake and repeat manually until you find the commit that does the regression :)

**Comment by Moulick** [comment]
in master branch its da0a5c25e7587292131895b34ff394e74075cd07

**Comment by gsemet** [comment]
soon fixed :)

**Comment by Moulick** [comment]
Yep, The latest commit fixes the problem.

**Comment by GianniGi** [comment]
Ubuntu 20.04 has a peculiar problem. Guake is transparent, but when I load vim, it loses the transparency :-D
