### ISSUE TITLE
Everytime I toggle Guake it adds an extra prompt line

### ISSUE THREAD

**Issue by sdban** [Guake/guake#823]
I am using Guake in Ubuntu 14.10. I have a setup where Guake starts at startup and I use `<F-12>` to toggle visibility.  

The issue is every-time I toggle visibility guake adds an extra line of prompt. For example 
after startup if I press <F-12> 4 times my Guake terminal shows : 
<pre><code> 
$
$
$
$
</pre></code>
where it should be showing just a single prompt  `$`. 
Other guake functionality is fine.  I cloned the latest build from github and followed the installation instructions. In case it is important I couldn't complete the `./dev.sh --install` script but I could use 
<code> ./autogen.sh && make... ` way.

**Comment by Stibbons** [comment]
Thanks for this reports. Thought this have been fixed...

**Comment by sdban** [comment]
Thank you for your response.  
I had previously guake (0.4?) installed from the ubuntu repositories which didn't have this issue.  I installed guake twice in less than three weeks from Github and had the same issue; (previously posted this on Stack Exchange)[http://askubuntu.com/questions/831338/a-quirky-issue-with-guake?noredirect=1#comment1266981_831338]. 
Also wanted to point out that the `dev.sh` script seems to get stuck midway during installation and I used the `./autogen.sh...` way.

**Comment by ntsim** [comment]
Seen this as well, but not all the time. It is usually guaranteed to happen in new prompts where you haven't done anything. 

On other prompts where you've done a few things, it doesn't exhibit this behaviour.

**Comment by Maardje** [comment]
I fixed this issue by adjusting my screen resolution to 1920 x 1080. I have a small high res screen. After setting the resolution to a lower one, the issue was solved for me. Hope it helps

**Comment by sdban** [comment]
@Maardje  My screen resolution has been always $1366\times 768$. The issue remains......

**Comment by Maardje** [comment]
@sdban hmm. Well I have the problem on 3200x1800 res but not on 1920x1080. Other than that I have no clue what the problem could be.
